[package]
name = "fawn"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = "0.2.15"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
ureq = { version = "3.1.2", features = ["json"] }
url = "2.5.7"
